"""
Core ID Detector Agent — Local CLIP-based inference.

Uses OpenAI's CLIP model (via HuggingFace Transformers) running entirely on
the local machine. No data ever leaves the device.

Pipeline: validation → preprocessing → CLIP zero-shot classification → structured output.

Three classification stages:
  1. ID vs. Not-ID (is this an identification document?)
  2. Document type (passport, national ID, driver's license, etc.)
  3. Authenticity (real photograph vs. AI-generated / digitally fabricated)
"""

from __future__ import annotations

import io
import logging
from pathlib import Path

import numpy as np
import torch
from PIL import Image, ImageFilter
from transformers import CLIPModel, CLIPProcessor

from . import config
from .exceptions import DetectionError, IDDetectorError
from .preprocessor import preprocess
from .schemas import DocumentType, IDDetectionResult
from .validator import validate_file

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Zero-shot prompt sets for CLIP classification
# ---------------------------------------------------------------------------

# Stage 1: Is this an ID document at all?
_ID_POSITIVE_PROMPTS = [
    "a photograph of an identification document",
    "a government issued identity card",
    "a passport document",
    "a driver's license card",
    "a national identity card with a photo",
    "an official ID card with text fields and a portrait photo",
    "a residence permit card",
    "a voter registration card",
    "a military identification card",
    "a student identification card",
    "a health insurance card with personal details",
]

_ID_NEGATIVE_PROMPTS = [
    "a photograph of a person",
    "a landscape photograph",
    "a photograph of food",
    "a screenshot of a website",
    "a photograph of an animal",
    "a blank piece of paper",
    "a photograph of a building",
    "a selfie photograph",
    "a photograph of text on a screen",
    "a business card",
    "a receipt or invoice",
    "a random object",
]

# Stage 2: Which type of ID document? (maps prompt → DocumentType)
_DOCTYPE_PROMPTS: dict[str, DocumentType] = {
    "a passport travel document with an MRZ code zone": DocumentType.PASSPORT,
    "a national identity card issued by a government": DocumentType.NATIONAL_ID,
    "a driver's license card for driving": DocumentType.DRIVER_LICENSE,
    "a residence permit card for foreign residents": DocumentType.RESIDENCE_PERMIT,
    "a voter identification card for elections": DocumentType.VOTER_ID,
    "a military identification card for armed forces": DocumentType.MILITARY_ID,
    "a student identification card from a university or school": DocumentType.STUDENT_ID,
    "a health insurance card or medical ID card": DocumentType.HEALTH_CARD,
    "an official identification document or card": DocumentType.OTHER_ID,
}

# Stage 3: Real photograph vs. AI-generated
_REAL_PROMPTS = [
    "a real photograph taken with a camera",
    "a genuine unedited photograph",
    "a real photo of a physical document on a table",
    "an authentic photograph with natural lighting",
    "a real camera photo with natural imperfections",
    "a scanned copy of a real document",
    "a photo taken with a phone camera of a real card",
]

_AI_GENERATED_PROMPTS = [
    "an AI generated image",
    "a computer generated fake image",
    "a digitally fabricated image created by artificial intelligence",
    "a deepfake image",
    "an image generated by stable diffusion or midjourney",
    "a synthetic image that looks artificial",
    "a photoshopped or digitally manipulated image",
    "a fake document created with AI image generation",
    "a rendered digital image that is not a real photograph",
]


class IDDetectorAgent:
    """
    AI-powered identification document detector and authenticity checker.

    Uses local CLIP model for:
    1. ID document classification (is this an ID?)
    2. Document type detection (passport, license, etc.)
    3. AI-generated image detection (real photo vs. fabricated)

    All inference runs on-device — no network calls, no API keys, no data leakage.

    Usage
    -----
    >>> from id_detector import IDDetectorAgent
    >>> agent = IDDetectorAgent()
    >>> result = agent.detect("path/to/image.jpg")
    >>> print(result.to_json())
    {
      "is_id_document": true,
      "confidence_score": 0.87,
      "document_type": "national_id",
      "is_authentic": true,
      "authenticity_score": 0.92,
      "reasoning": "...",
      "risk_flags": []
    }
    """

    def __init__(
        self,
        *,
        model_name: str | None = None,
        device: str | None = None,
        max_file_size_bytes: int | None = None,
        id_threshold: float | None = None,
        authenticity_threshold: float | None = None,
    ):
        """
        Initialize the ID Detector Agent.

        Parameters
        ----------
        model_name : str | None
            HuggingFace CLIP model name. Defaults to config.CLIP_MODEL_NAME.
            The model is downloaded on first use and cached locally.
        device : str | None
            Torch device ("cpu", "cuda", "mps"). Auto-detected if None.
        max_file_size_bytes : int | None
            Max input file size in bytes. Defaults to config.MAX_FILE_SIZE_BYTES.
        id_threshold : float | None
            Confidence threshold to classify as ID. Defaults to config.ID_THRESHOLD.
        authenticity_threshold : float | None
            Threshold above which an image is considered authentic (real photo).
            Defaults to config.AUTHENTICITY_THRESHOLD.
        """
        self._model_name = model_name or config.CLIP_MODEL_NAME
        self._max_file_size = max_file_size_bytes or config.MAX_FILE_SIZE_BYTES
        self._id_threshold = id_threshold or config.ID_THRESHOLD
        self._auth_threshold = authenticity_threshold or config.AUTHENTICITY_THRESHOLD

        # Auto-detect device
        if device:
            self._device = device
        elif torch.cuda.is_available():
            self._device = "cuda"
        else:
            self._device = "cpu"

        # Load CLIP model and processor
        try:
            logger.info(
                "Loading CLIP model '%s' on device '%s'...",
                self._model_name,
                self._device,
            )
            self._processor = CLIPProcessor.from_pretrained(self._model_name)
            self._model = CLIPModel.from_pretrained(self._model_name).to(self._device)
            self._model.eval()
            logger.info("CLIP model loaded successfully.")
        except Exception as exc:
            raise DetectionError(
                message=f"Failed to load CLIP model '{self._model_name}': {exc}",
                detail="Ensure you have internet for the first download. Model is cached after that.",
            ) from exc

    def detect(
        self,
        source: str | Path | bytes,
        *,
        mime_type: str | None = None,
    ) -> IDDetectionResult:
        """
        Analyze an image or PDF and return an ID detection + authenticity result.

        Parameters
        ----------
        source : str | Path | bytes
            File path or raw bytes of the image/PDF.
        mime_type : str | None
            Optional MIME type hint. If source is bytes and no mime_type is
            provided, magic-byte detection is used.

        Returns
        -------
        IDDetectionResult
            Structured detection result with confidence score and authenticity.

        Raises
        ------
        InvalidFileError, FileTooLargeError, UnsupportedFormatError
            On input validation failures.
        DetectionError
            On model inference failures.
        """
        # 1. Validate
        data, detected_mime = validate_file(
            source, max_size_bytes=self._max_file_size
        )
        if mime_type:
            detected_mime = mime_type

        # 2. Preprocess
        processed_data, processed_mime = preprocess(data, detected_mime)

        # 3. Run local CLIP inference (all 3 stages)
        return self._classify(processed_data)

    def detect_batch(
        self,
        sources: list[str | Path | bytes],
    ) -> list[IDDetectionResult]:
        """
        Analyze multiple images/PDFs sequentially.

        Parameters
        ----------
        sources : list[str | Path | bytes]
            List of file paths or raw bytes.

        Returns
        -------
        list[IDDetectionResult]
            One result per input, in the same order.
            Failed detections are returned as error results rather than raising.
        """
        results: list[IDDetectionResult] = []
        for i, source in enumerate(sources):
            try:
                results.append(self.detect(source))
            except IDDetectorError as exc:
                logger.error("Batch item %d failed: %s", i, exc.message)
                results.append(
                    IDDetectionResult(
                        is_id_document=False,
                        confidence_score=0.0,
                        document_type="not_an_id",
                        is_authentic=False,
                        authenticity_score=0.0,
                        reasoning=f"Detection failed: {exc.message}",
                        risk_flags=["processing_error"],
                    )
                )
        return results

    # ------------------------------------------------------------------
    # Internal CLIP classification pipeline
    # ------------------------------------------------------------------

    def _get_clip_scores(self, image: Image.Image, text_prompts: list[str]) -> np.ndarray:
        """Compute CLIP cosine-similarity scores between an image and text prompts."""
        inputs = self._processor(
            text=text_prompts,
            images=image,
            return_tensors="pt",
            padding=True,
        )
        inputs = {k: v.to(self._device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self._model(**inputs)

        # logits_per_image shape: (1, num_prompts)
        logits = outputs.logits_per_image.squeeze(0).cpu().numpy()
        return logits

    def _classify(self, image_bytes: bytes) -> IDDetectionResult:
        """Run the full 3-stage CLIP classification pipeline."""
        try:
            image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        except Exception as exc:
            raise DetectionError(
                message=f"Cannot open image: {exc}",
                detail=str(exc),
            ) from exc

        try:
            # =============================================================
            # Stage 1: ID vs. Not-ID
            # =============================================================
            all_prompts = _ID_POSITIVE_PROMPTS + _ID_NEGATIVE_PROMPTS
            logits = self._get_clip_scores(image, all_prompts)
            probs = _softmax(logits)

            n_pos = len(_ID_POSITIVE_PROMPTS)
            id_prob = float(np.sum(probs[:n_pos]))
            non_id_prob = float(np.sum(probs[n_pos:]))
            confidence = id_prob / (id_prob + non_id_prob)
            is_id = confidence >= self._id_threshold

            # =============================================================
            # Stage 2: Document type sub-classification
            # =============================================================
            doc_type = DocumentType.NOT_AN_ID
            type_reasoning = ""

            if is_id:
                type_prompts = list(_DOCTYPE_PROMPTS.keys())
                type_logits = self._get_clip_scores(image, type_prompts)
                type_probs = _softmax(type_logits)

                best_idx = int(np.argmax(type_probs))
                best_prompt = type_prompts[best_idx]
                doc_type = _DOCTYPE_PROMPTS[best_prompt]
                type_score = float(type_probs[best_idx])
                type_reasoning = (
                    f" Document type: {doc_type.value} "
                    f"(best match: '{best_prompt}', score={type_score:.3f})."
                )

            # =============================================================
            # Stage 3: Authenticity — real photo vs. AI-generated
            # =============================================================
            auth_prompts = _REAL_PROMPTS + _AI_GENERATED_PROMPTS
            auth_logits = self._get_clip_scores(image, auth_prompts)
            auth_probs = _softmax(auth_logits)

            n_real = len(_REAL_PROMPTS)
            real_prob = float(np.sum(auth_probs[:n_real]))
            fake_prob = float(np.sum(auth_probs[n_real:]))
            authenticity_score = real_prob / (real_prob + fake_prob)
            is_authentic = authenticity_score >= self._auth_threshold

            # Top AI-generated prompt matches (for reasoning)
            top_fake = sorted(
                zip(_AI_GENERATED_PROMPTS, auth_probs[n_real:].tolist()),
                key=lambda x: x[1],
                reverse=True,
            )[:2]
            auth_reasoning = (
                f" Authenticity: score={authenticity_score:.3f} "
                f"(threshold={self._auth_threshold}). "
            )
            if not is_authentic:
                fake_matches = ", ".join(f"'{p}' ({s:.3f})" for p, s in top_fake)
                auth_reasoning += f"Top AI indicators: {fake_matches}."

            # =============================================================
            # Stage 4: Risk flag analysis (image quality heuristics)
            # =============================================================
            risk_flags = _analyze_risk_flags(image)

            # Add AI-generated flag if detected
            if not is_authentic:
                risk_flags.append("ai_generated")

            # =============================================================
            # Build reasoning string
            # =============================================================
            top_positive = sorted(
                zip(_ID_POSITIVE_PROMPTS, probs[:n_pos].tolist()),
                key=lambda x: x[1],
                reverse=True,
            )[:3]
            top_matches = ", ".join(f"'{p}' ({s:.3f})" for p, s in top_positive)

            reasoning = (
                f"CLIP classification — "
                f"ID confidence={confidence:.3f} (threshold={self._id_threshold}). "
                f"Top ID prompts: {top_matches}."
                f"{type_reasoning}{auth_reasoning}"
            )

            if risk_flags:
                reasoning += f" Risk flags: {', '.join(risk_flags)}."

            result = IDDetectionResult(
                is_id_document=is_id,
                confidence_score=round(confidence, 4),
                document_type=doc_type,
                is_authentic=is_authentic,
                authenticity_score=round(authenticity_score, 4),
                reasoning=reasoning,
                risk_flags=risk_flags,
            )

            logger.info(
                "Detection complete: is_id=%s, confidence=%.4f, type=%s, "
                "authentic=%s, auth_score=%.4f",
                result.is_id_document,
                result.confidence_score,
                result.document_type,
                result.is_authentic,
                result.authenticity_score,
            )
            return result

        except IDDetectorError:
            raise
        except Exception as exc:
            raise DetectionError(
                message=f"CLIP inference failed: {type(exc).__name__}: {exc}",
                detail=str(exc),
            ) from exc


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _softmax(logits: np.ndarray) -> np.ndarray:
    """Numerically stable softmax."""
    exp = np.exp(logits - np.max(logits))
    return exp / exp.sum()


def _analyze_risk_flags(image: Image.Image) -> list[str]:
    """
    Analyze image quality to detect potential risk indicators.

    Uses PIL-based heuristics — no model call needed.
    """
    flags: list[str] = []
    w, h = image.size

    # Low resolution
    if min(w, h) < 200:
        flags.append("low_resolution")

    # Blur detection via Laplacian variance
    try:
        gray = image.convert("L")
        laplacian = gray.filter(ImageFilter.Kernel(
            size=(3, 3),
            kernel=[-1, -1, -1, -1, 8, -1, -1, -1, -1],
            scale=1,
            offset=128,
        ))
        lap_array = np.array(laplacian, dtype=np.float32) - 128.0
        variance = float(np.var(lap_array))
        if variance < 50.0:
            flags.append("blurry_image")
    except Exception:
        pass  # Non-critical — skip if analysis fails

    # Aspect ratio check (extremely wide/tall might be a partial scan)
    aspect = max(w, h) / max(min(w, h), 1)
    if aspect > 4.0:
        flags.append("partial_document")

    # Screenshot detection (common screen resolutions)
    screen_resolutions = {
        (1920, 1080), (1080, 1920), (2560, 1440), (1440, 2560),
        (1366, 768), (768, 1366), (1280, 720), (720, 1280),
        (3840, 2160), (2160, 3840),
    }
    if (w, h) in screen_resolutions:
        flags.append("possible_screenshot")

    return flags
